type Query {
    orders: [Order!]!
}

type Mutation {
    addCategory(
        name: String!
    ): Response!

    updateCategory(
        category_id: ID!
        name: String!
    ): Response!

    deleteCategory(
        category_id: ID!
    ):Response!
}

type Order{
    order_id: ID!
    user_id: ID!
    products: [Product!]!
    totalPrice: Int!
    ispad: Boolean!
}

type Response {
	status: Int!
	message: String!
	category: Category!
}