type Query {
    users(
        user_id: ID
        search: String
    ): [User!]!
}

type Mutation {
	register(username: String! password: String! contact: String! email: String!): authResponse!
	updateUser(user_id: ID! username: String password: String contact: String email: String): Response!
	deleteUser(user_id: ID!): Response!
    login(username: String! password: String!): authResponse!
}

type User{
    user_id: ID!
    username: String!
    contact: Contact!
    email: Email!
    role: String!
}

type authResponse{
    status: Int!
    message: String!
    token: Any
}
