input Pagination {
	page: Int = 1
	limit: Int = 2
}

input Filter {
    category_id: ID
    name: String
    from: Int
    to: Int
}

type Query {
    products(
        product_id: ID
        filter: Filter = {}
        search: String
        pagination: Pagination = {}
    ): [Product!]!
}

type Mutation {
    addProduct(
        category_id: ID!
        name: String!
        price: Int!
        short_info: String!
        long_info: String!
        file: Upload!
    ): Response!

    updateProduct(
        product_id: ID!
        category_id: ID
        name: String
        price: Int
        short_info: String 
        long_info: String
        file: Upload
    ): Response!

    deleteProduct(
        product_id: ID!
    ):Response!
}

type Product{
    product_id: ID!
    category_id: ID!
    name: String!
    price: Int!
    short_info: String!
    long_info: String!
    img_url: String!
}