type Query {
    categories: [Category!]!
}

type Mutation {
    addCategory(
        name: String!
    ): Response!

    updateCategory(
        category_id: ID!
        name: String!
    ): Response!

    deleteCategory(
        category_id: ID!
    ):Response!
}

type Category{
    category_id: ID!
    name: String!
}